// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace GYM.Models;

public partial class Booking
{
    public Booking()
    {
        // Set BookingDate to current UTC time by default
        BookingDate = DateTime.Now;
    }

    public int Id { get; set; }

    [Required]
    [DisplayName("Course Id")]
    public int? CourseId { get; set; }

    [Required]
    [StringLength(20, ErrorMessage = "The {0} must be less than 20 word")]
    [DisplayName("Course Name")]
    public string CourseName { get; set; }

    [Required]
    [DisplayName("User Id")]
    public int? UserId { get; set; }

    [Required]
    [StringLength(20, ErrorMessage = "The {0} must be less than 20 word")]
    [DisplayName("User Name")]
    public string Username { get; set; }

    [DisplayName("Booking Date")]
    [DataType(DataType.DateTime)]
    public DateTime? BookingDate { get; set; }
}