// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace GYM.Models;

public partial class RecordCalorie
{
    public RecordCalorie() {
        RecordDate = DateTime.Now;
    }  

    public int Id { get; set; }

    [Required]
    [StringLength(20, ErrorMessage = "The {0} must be less than 20 word")]
    [DisplayName("Event Name")]
    public string EventName { get; set; }

    [Required]
    [StringLength(20, ErrorMessage = "The {0} must be less than 20 word")]
    [DisplayName("Event Type")]
    public string EventType { get; set; }

    [Required]
    public int? Calorie { get; set; }

    [Required]
    [StringLength(20, ErrorMessage = "The {0} must be less than 20 word")]
    [DisplayName("User Name")]
    public string Username { get; set; }

    [Required]
    [DisplayName("User Id")]
    public int? UserId { get; set; }

    public DateTime? RecordDate { get; set; }
}